M48
; DRILL file {KiCad (6.0.10)} date Fri Feb 17 12:04:38 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T12:04:38-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.3Y-3.8
X5.4Y-3.5
X5.5Y-3.6
X5.6Y-3.4
X5.7Y-3.8
X5.8Y-3.1
X5.8Y-3.5
X5.8Y-4.2
X6.1Y-3.4
X6.3Y-3.6
T2
X5.1Y-3.6
X5.1Y-3.8
T0
M30
